# Generated by Django 4.0.3 on 2022-05-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimg',
            field=models.ImageField(default='media/default/def.jpg', upload_to='mdedia/profilepics'),
        ),
    ]
