# Generated by Django 4.0.3 on 2022-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_image', models.ImageField(upload_to='cat_media/Readercat_image')),
                ('category_desc', models.TextField()),
                ('catagory_update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
