# Generated by Django 4.0.3 on 2022-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.CharField(max_length=150)),
                ('invoice_id', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
