# Generated by Django 4.0.3 on 2022-05-20 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_profile_pimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_order_cart_ids_order_cust_id_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('rev', models.TextField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.profile')),
                ('ratpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
