# Generated by Django 4.0.3 on 2022-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
