# Generated by Django 4.0.3 on 2022-05-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contnum',
            field=models.PositiveBigIntegerField(),
        ),
    ]
